version: 2


build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  apt_packages:
    - python3-pyqt5
    - qt5-qmake
python:
  # Install our python package before building the docs
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .    
sphinx:
  fail_on_warning: false
formats:
  - pdf
