[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DeepEthoProfile"
authors = [{name = "Andrei Istudor", email = "andrei.istudor@hu-berlin.de"}]
dynamic = ["name", "version", "authors"]
