# script to builds a base Docker image containing the software environment needed to run the processing

#FROM nvidia/cuda:11.4.3-cudnn8-runtime-ubuntu20.04
FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
#ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED 1

#Update packages and install basics
RUN apt-get -y -qq update && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq wget unzip git dialog apt-utils nano ffmpeg x264
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python3 python3-venv

RUN  apt-get clean && rm -rf /var/lib/apt

#WORKDIR /app/
RUN mkdir /opt/venv
RUN python3 -m venv /opt/venv
# Enable venv
ENV PATH="/opt/venv/bin:$PATH"

#RUN python3 -m venv /
RUN pip3 install --upgrade pip
RUN pip3 install -U numpy matplotlib pandas scikit-image scikit-learn scipy av opencv-python
RUN pip3 install torch torchvision
#--index-url https://download.pytorch.org/whl/cu126

RUN mkdir /home/nn 
WORKDIR /home/nn

